---
title: "scratch"
author: "Tyler Cobian"
date: "2/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```



```{r}
library(kableExtra)
library(tidyverse)
library(shiny)
library(ggpubr)
library(shinydashboard)
library(shinythemes)
library(tmap)
library(sf)
library(leaflet)

crops<- read_csv("Total_Crops.csv")
```


```{r}
crops<- read_csv("Total_Crops.csv")
kernza_sens<- read_csv("kernza_updated.csv")
bison_sens<- read_csv("bison_compiling_sensativity.csv")
mango_sens<- read_csv("MANGO_sens.csv")
sensativity<- read_csv("diversity_sensativity.csv")
```



Widget #1
```{r}
map_data<- tribble(
    ~id, ~lon, ~lat,
    "Cotton", -95.300003, 32.349998,
    "Cotton", 87.5396, 42.5246,
    "Cotton", 78.6569, 22.9734,
    "Cotton", -80.6549, -5.1783,
    "Bison Grazing", -103.2310, 44.0805,
    "Bison Grazing", -56.9211, -12.6819,
    "Mango", 72.8777, 19.0760,
    "Mango", -85.2072, 12.8654,
    "Kernza", -94.6859, 46.7296,
    "Kernza", -98.4842, 39.0119
  )

  map_data_sf<- st_as_sf(map_data, coords = c("lon", "lat"))
  
  
map_1<- leaflet(map_data) %>% 
  addProviderTiles("CartoDB.DarkMatter") %>% 
  addCircleMarkers(lng =~lon, lat =~lat, popup = ~id, color = 'red')
map_1
```

Tables for map
```{r}
cotton_regen_table<- crops %>% 
  filter(Crop == "Cotton") %>% 
  filter(Country == "India") %>%
  filter(Practice == "Regenerativeerative") %>% 
  summarise(mean_regen_soc = mean(dSOC),
            mean_regen_gwp = mean(GWP))

cotton_organic_table<- crops %>% 
  filter(Crop == "Cotton") %>% 
  filter(Country == "India") %>%
  filter(Practice == "Organic") %>% 
  summarise(mean_regen_soc = mean(dSOC),
            mean_regen_gwp = mean(GWP))

cotton_india<- bind_rows(cotton_regen_table, cotton_organic_table)
colnames(cotton_india)<- c("Average kgSOC", "Average kgCO2e")
rownames(cotton_india)<- c("Regenerative ", "Organic")

cotton_table<- kable(cotton_india) %>% 
  kable_styling(bootstrap_options = "striped")
cotton_table




```



Graph for the breakdown of GHGs
```{r}
options(scipen = 999)
# find the mean n2o and ch4 for regen and oragnic for each crop in the base site
# base sites 
# Kernza: Minnesota
# Mango: Nicaragua
# Cotton: Texas
# Bison: Sputh Dakota
kernza_regen_n2o<- sum(crops$N2O_CO2e[55:72])
kernza_organic_n2o<- sum(crops$N2O_CO2e[37:54])
kernza_regen_ch4<- sum(crops$CH4_CO2e[55:72])
kernza_organic_ch4<- sum(crops$CH4_CO2e[37:54])
kernza_regen_co2<- (sum(crops$CO2e[55:72]))
kernza_organic_co2<- (sum(crops$CO2e[37:54]))

mango_regen_n2o<- sum(crops$N2O_CO2e[639:656])
mango_organic_n2o<- sum(crops$N2O_CO2e[657:674])
mango_regen_ch4<- sum(crops$CH4_CO2e[639:656])
mango_organic_ch4<- sum(crops$CH4_CO2e[657:674])
mango_regen_co2<- sum(crops$CO2e[639:656])
mango_organic_co2<- sum(crops$CO2e[657:674])

cotton_regen_n2o<- sum(crops$N2O_CO2e[217:234])
cotton_organic_n2o<- sum(crops$N2O_CO2e[145:162])
cotton_regen_ch4<- sum(crops$CH4_CO2e[217:234])
cotton_oragnic_ch4<- sum(crops$CH4_CO2e[145:162])
cotton_regen_co2<- sum(crops$CO2e[217:234])
cotton_organic_co2<- sum(crops$CO2e[145:162])

bison_regen_n2o<- sum(crops$N2O_CO2e[585:602])
bison_organic_n2o<- sum(crops$N2O_CO2e[567:584])
bison_regen_ch4<- sum(crops$CH4_CO2e[585:602])
bison_organic_ch4<- sum(crops$CH4_CO2e[567:584])
bison_regen_co2<- sum(crops$CO2e[585:602])
bison_organic_co2<- sum(crops$CO2e[567:584])

# make a data set of these averages

n2o_ch4_co2<- data.frame(Crop = c("Kernza", "Kernza", "Kernza", "Kernza","Kernza", "Kernza", "Mango", "Mango","Mango", "Mango","Mango", "Mango","Cotton", "Cotton", "Cotton", "Cotton", "Cotton", "Cotton","Bison", "Bison", "Bison", "Bison", "Bison", "Bison"),
                   Practice = c("Regenerative", "Organic", "Regenerative", "Organic", "Regenerative", "Organic", "Regenerative", "Organic"),
                   Gas = c("N2O", "N2O", "CH4", "CH4","CO2","CO2", "N2O", "N2O", "CH4", "CH4","CO2","CO2","N2O", "N2O", "CH4", "CH4","CO2","CO2", "N2O", "N2O", "CH4", "CH4", "CO2","CO2"),
                   kg_co2e = c(kernza_regen_n2o, kernza_organic_n2o, kernza_regen_ch4, kernza_organic_ch4, kernza_regen_co2, kernza_organic_co2, mango_regen_n2o, mango_organic_n2o, mango_regen_ch4, mango_organic_ch4, mango_regen_co2, mango_organic_co2, cotton_regen_n2o, cotton_organic_n2o, cotton_regen_ch4, cotton_oragnic_ch4, cotton_regen_co2, cotton_organic_co2, bison_regen_n2o, bison_organic_n2o, bison_regen_ch4, bison_organic_ch4, bison_regen_co2, bison_organic_co2))

ch4_n20_kernza<- n2o_ch4_co2 %>% 
  filter(Crop == "Kernza") %>% 
  group_by(Practice)

ch4_n20_cotton<- n2o_ch4_co2 %>% 
  filter(Crop == "Cotton") %>% 
  group_by(Practice)

ch4_n20_mango<- n2o_ch4_co2 %>% 
  filter(Crop == "Mango") %>% 
  group_by(Practice)

ch4_n20_bison<- n2o_ch4_co2 %>% 
  filter(Crop == "Bison") %>% 
  group_by(Practice)

ch4_n20_kernza_plot<- ggplot(ch4_n20_kernza, aes(y = kg_co2e, x = Gas, fill = Gas))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
  facet_wrap(~Practice)+
  scale_fill_manual(values = c("darkolivegreen", "darkolivegreen3", "darkolivegreen1"))+
  geom_hline(yintercept = 0)+
  labs(title = "KERNZA", y = "kgCO2e/ha", x = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = 30), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), axis.title.x = element_text(size = 20), strip.text = element_text(size = 20), axis.title.y = element_text(size = 20))
ch4_n20_kernza_plot

ch4_n20_cotton_plot<- ggplot(ch4_n20_cotton, aes(y = kg_co2e, x = Gas, fill = Gas))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
  facet_wrap(~Practice)+
  scale_fill_manual(values = c("deepskyblue", "deepskyblue3", "deepskyblue4"))+
  labs(title = "COTTON", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = 30), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), strip.text = element_text(size = 20))
ch4_n20_cotton_plot

ch4_n20_mango_plot<- ggplot(ch4_n20_mango, aes(y = kg_co2e, x = Gas, fill = Gas))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
  facet_wrap(~Practice)+
  scale_fill_manual(values = c("darkorange", "darkorange3", "darkorange4"))+
  labs(title = "MANGO", y = "kgCO2e/ha", x = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = 30), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), axis.title.x = element_text(size = 20), strip.text = element_text(size = 20), axis.title.y = element_text(size = 20))
ch4_n20_mango_plot

ch4_n20_bison_plot<- ggplot(ch4_n20_bison, aes(y = kg_co2e, x = Gas, fill = Gas))+
  geom_bar(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
  facet_wrap(~Practice)+
  scale_fill_manual(values = c("darkslategray", "darkseagreen3", "darkseagreen4"))+
  labs(title = "GRAZING", y = element_blank(), x = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = 30), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), strip.text = element_text(size = 20))
ch4_n20_bison_plot

ggarrange(ch4_n20_kernza_plot, ch4_n20_cotton_plot, ch4_n20_mango_plot, ch4_n20_bison_plot)
```


Second try for GHG plots
```{r}
kernza<- crops %>% 
  filter(Crop == "Kernza")

cotton<- crops %>% 
  filter(Crop == "Cotton") %>% 
  filter(Practice == "Regenerativeerative" | 
         Practice == "Organic")

mango<- crops %>% 
  filter(Crop == "Mango")

grazing<- crops %>% 
  filter(Crop == "Bison")

crops_filter<- bind_rows(kernza, cotton, mango, grazing)
  
```

Mango Bar location plot
```{r}
mango_location<- data.frame(Location = c("India", "India","Nicaragua", "Nicaragua"),
                             Practice = c("Regenerative", "Organic","Regenerative", "Organic"),
                             SOC = c(mango_india_regen_soc, mango_india_organic_soc, mango_nicaragua_regen_soc, mango_nicaragua_organic_soc),
                           GWP = c(mango_india_regen_gwp, mango_india_organic_gwp, mango_nicaragua_regen_gwp, mango_nicaragua_organic_gwp))

# make the plots

mango_location_soc_plot<- ggplot(mango_location, aes(y = SOC, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  labs(title = "MANGO", y = "kgSOC/ha", x = element_blank())+
  geom_hline(yintercept = 0)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = 30), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), legend.text = element_text(size = 25), legend.title = element_text(size = 25))
mango_location_soc_plot

mango_location_gwp_plot<- ggplot(mango_location, aes(y = GWP, x = Location, fill = Practice))+
  geom_bar(stat = "identity", position = "dodge", width = 0.5)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  geom_hline(yintercept = 0)+
  labs(title = "MANGO", y = "kgCO2e/ha", x = element_blank())+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = 30), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), legend.text = element_text(size = 25), legend.title = element_text(size = 25))
mango_location_gwp_plot
```




```{r}
mango_regen_nic = mango %>%
  filter(Country == "Nicaragua") %>%
  filter(Practice == "Regenerative")

avg_soc_nic_r = mean(mango_regen_nic$dSOC)
avg_ghg_nic_r = mean(mango_regen_nic$GWP)


mango_org_nic = mango %>% 
  filter(Country == "Nicaragua") %>% 
  filter(Practice == "Organic")

avg_soc_nic_o = mean(mango_org_nic$dSOC)
avg_ghg_nic_o = mean(mango_org_nic$GWP)

mango_regen_india = mango %>%
  filter(Country == "India") %>%
  filter(Practice == "Regenerative")

mean(mango_regen_india$dSOC)
mean(mango_regen_india$GWP)

mango_org_india = mango %>% 
  filter(Country == "India") %>% 
  filter(Practice == "Organic")

mean(mango_org_india$dSOC)
mean(mango_org_india$GWP)

```


```{r}
nic_mango = data.frame(Crop = c("Mango", "Mango"),
           Practice = c("Regenerative", "Organic"),
           Country = c("Nicaragua", "Nicaragua"),
           mean_soc = c(avg_soc_nic_r, avg_soc_nic_o),
           mean_ghg = c(avg_ghg_nic_r, avg_ghg_nic_o)
)

ggplot(data = nic_mango, aes(x = Practice, y = mean_soc))+
  geom_col(aes(fill = Practice), width = 0.5)+
  scale_fill_manual(values = c("darkorange4", "darkorange"))+
  theme_classic()


```


Widget 3
```{r}
#Cumulative graph
practices <- crops %>% 
  group_by(Crop, Country, Practice) %>% 
  summarise(sum_dSOC = sum(dSOC),
            sum_GWP = sum(GWP)) %>% 
  filter(Practice == "Monocrop" |
         Practice == "Twocrops" | 
         Practice == "Threecrops" |
         Practice == "Fourcrops")
  
output$practice_plot<- renderPlot({
  ggplot(data = practice_df(), aes(x = Practice, y = sum_dSOC, fill = Gas))+
    geom_bar(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
    scale_fill_manual(values = c("darkolivegreen", "darkolivegreen3", "darkolivegreen1"))+
    labs(title = "Average Yearly GHG Emissions", x = "Emissions from Each Gas")+
    theme_minimal()
})



practices_yearly <- crops %>% 
  group_by(Crop, Country, Practice) %>% 
  filter(Practice == "Monocrop" |
           Practice == "Twocrops" | 
           Practice == "Threecrops" |
           Practice == "Fourcrops") %>% 
  select(Year, Crop, Country, Practice, dSOC, GWP)

practice_df <- reactive({
    practices_mean %>% 
      filter(Crop == input$practices_crops)
  })

cols <- reactive({
  cols <- c("1" = "grey", "2" =  "grey", "3" =  "grey",
            "4" =  "grey", "5" = "grey")
  cols[input$practices_number] <- "deepskyblue4"
  return(cols)
})

label <- reactive({
  practices_mean %>% 
    filter(Crop == input$practices_crops) %>% 
    filter(Practice == input$practices_number) 
  
})

cols2 <- reactive({
  cols2 <- c("1" = "grey", "2" =  "grey", "3" =  "grey",
            "4" =  "grey", "5" = "grey")
  cols2[input$practices_number] <- "darkolivegreen3" 
  return(cols2)
})

output$practice_mean_dSOC <- renderPlot({
  ggplot(data = practice_df(), aes(x = Practice, y = mean_dSOC, fill = factor(Practice))) +
    geom_col(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
    scale_colour_manual(values = cols(), aesthetics = c("colour", "fill"))+
    labs(title = "Effect of cover cropping on average change in SOC", x = "Number of crops", y = "Average change in SOC (kgSOC/ha)")+
    theme_minimal() + 
    geom_text(data = label(), aes(label = round(mean_dSOC, digits = 0)), vjust = -1, position = position_dodge(width = 1), color = "deepskyblue4")
})

output$practice_mean_GWP <- renderPlot({
  ggplot(data = practice_df(), aes(x = Practice, y = mean_GWP, color = factor(Practice), fill = factor(Practice))) +
    geom_col(stat = "identity", position = "dodge", show.legend = "False", width = 0.5)+
    scale_colour_manual(values = cols2(), aesthetics = c("colour", "fill"))+
    labs(title = "Effect of cover cropping on average change in GHG emissions", x = "Number of crops", y = "Average change in GHG emissions (kg CO2e)")+
    theme_minimal() + 
    geom_text_repel(data = label(), aes(label = round(mean_GWP, digits = 0)), color = "darkgreen", direction = "y", position = position_dodge(width = 1))
})



  observe({
    updateSelectInput(session,
                      "practices_number",
                      choices = practices_mean %>% 
                        filter(Practice == input$practices_number) %>%
                        select(Practice) %>% 
                        unique()
    )
  }) 


```



```{r}

ghg_break_down<- crops %>% 
  group_by(Crop, Country, Practice) %>% 
  summarise(CO2 = mean(CO2e),
            CH4 = mean(CH4_CO2e),
            N2O = mean(N2O_CO2e)) %>% 
  filter(Practice == "Organic" |
         Practice == "Regenerative") %>% 
  gather("Gas", "kgCO2e", 4:6)


ghg_total<- crops %>%
  group_by(Crop, Practice, Country) %>% 
  summarise(GHG = mean(GWP)) %>% 
  filter(Practice == "Organic" |
         Practice == "Regenerative")
ghg_total

ghg_table<- kable(ghg_break_down) %>% 
    kable_styling(bootstrap_options = c("striped", "hover"))

ghg_table


```



```{r}
kernza_sens<- read_csv("kernza_updated.csv")
bison_sens<- read_csv("bison_compiling_sensativity.csv")
mango_sens<- read_csv("MANGO_sens.csv")
```


Make one data set with all the crop sensativity tests
```{r}
cotton_sens<- crops %>% 
  filter(Crop == "Cotton") %>% 
  filter(Country == "India") %>% 
  filter(Practice == "Monocrop" |
           Practice == "Twocrops"|
           Practice == "Threecrops" |
           Practice == "Fourcrops" |
           Practice == "Regenerative") %>% 
  select(-Country)


mango_sens
mango_sens$Crop<- "Mango"


bison_sens_1<- bison_sens %>% 
  filter(crops_practices != "compost") %>% 
  select(-site)


bison_sens_1$crops_practices[1:20]<- "Monocrop"
bison_sens_1$crops_practices[21:40]<- "Twocrops"
bison_sens_1$crops_practices[41:60]<- "Threecrops"
bison_sens_1$crops_practices[61:80]<- "Fourcrops"
bison_sens$Crop<- "Bison"


kernza_sens_1<- kernza_sens %>% 
  filter(Practice == "Compost"|
         Practice == "Alfalfa"|
         Practice == "Tree"|
         Practice == "Regen")
kernza_sens_1$Practice[1:18]<- "Monocrop"
kernza_sens_1$Practice[18:36]<- "Twocrops"
kernza_sens_1$Practice[37:54]<- "Threecrops"
kernza_sens_1$Practice[55:72]<- "Regenerative"
kernza_sens_1$Crop<- "Kernza"


sensativity<- read_csv("diversity_sensativity.csv")

practices_yearly <- sensativity %>% 
  filter(Practice == "Monocrop" |
           Practice == "Twocrops" | 
           Practice == "Threecrops" |
           Practice == "Fourcrops"|
           Practice == "Regenerative") %>% 
  mutate(Practice = case_when(
    Practice == "Monocrop" ~ 1,
    Practice == "Twocrops" ~ 2,
    Practice == "Threecrops" ~ 3,
    Practice == "Fourcrops" ~ 4,
    Crop == "Cotton" & Practice == "Regenerative" ~ 5,
    Crop == "Bison" & Practice == "Regenerative" ~ 5,
    Crop == "Kernza" & Practice == "Regenerative" ~ 4,
    Crop == "Mango" & Practice == "Regenerative" ~ 3)) %>% 
  select(Year, Crop, Country, Practice, dSOC, GWP) %>% 
  arrange(Practice)


practices_sum <- sensativity %>%  
  group_by(Crop, Country, Practice) %>% 
  summarise(mean_dSOC = mean(dSOC),
            mean_GWP = mean(GWP))%>% 
  filter(Practice == "Monocrop" |
           Practice == "Twocrops" | 
           Practice == "Threecrops" |
           Practice == "Fourcrops") %>% 
  mutate(Practice = case_when(
    Practice == "Monocrop" ~ 1,
    Practice == "Twocrops" ~ 2,
    Practice == "Threecrops" ~ 3,
    Practice == "Fourcrops" ~ 4)) %>% 
  arrange(Practice)


practice_sum_dSOC <-ggplot(data = practices_sum, aes(x = Practice, y = mean_dSOC, color = factor(Practice), fill = factor(Practice)))+
  geom_col(position = "dodge", show.legend = "False", width = 0.5)
practice_sum_dSOC

```


```{r}
cotton_regen_texas_table<- crops %>% 
  filter(Crop == "Cotton") %>% 
  filter(Country == "Texas") %>%
  filter(Practice == "Regenerative") %>% 
  summarise(mean_regen_soc = mean(dSOC),
            mean_regen_gwp = mean(GWP))

cotton_organic_texas_table<- crops %>% 
  filter(Crop == "Cotton") %>% 
  filter(Country == "Texas") %>%
  filter(Practice == "Organic") %>% 
  summarise(mean_regen_soc = mean(dSOC),
            mean_regen_gwp = mean(GWP))

cotton_texas<- bind_rows(cotton_regen_texas_table, cotton_organic_texas_table)
colnames(cotton_texas)<- c("Yearly Change kgSOC", "Average Net GHG kgCO2e")
rownames(cotton_texas)<- c("Regenerative ", "Organic")

cotton_texas_table<- kable(cotton_texas, caption = "Cotton: Texas") %>% 
  kable_styling(bootstrap_options = "striped")
cotton_texas_table
```





